<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
$_max_bestsellers = 5;
?>
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>

<?php echo $this->getToolbarHtml() ?>

<?php $_iterator = 0; ?>
<ul>
<?php 
foreach ($_productCollection as $_product): 
    $_iterator++;
    if ($_iterator > $_max_bestsellers)
        continue;
    ?>
        <li>&bull; <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></li>
    <?php
endforeach;
?>
</ul>

<?php echo $this->getToolbarHtml() ?>
<?php endif; ?>
