<div class="header-container">
    <div class="header">
        <div class="header-top-container">
            <div class="header-top">
                <?php if ($this->getIsHomePage()):?>
                <h1 id="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
                <?php else:?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
                <?php endif?>
                <div class="quick-access">
                    <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?></p>
                    <?php echo $this->getChildHtml('topLinks') ?>
                    <?php echo $this->getChildHtml('store_language') ?>
                </div>
                <?php echo $this->getChildHtml('topSearch') ?>
                <?php echo $this->getChildHtml('topContainer'); ?>
            </div>
        </div>
        <div class="header-nav-container">
            <div class="header-nav">
                <?php echo $this->getChildHtml('topMenu') ?>
            </div>
        </div>
    </div>
</div>
