<div class="footer-container">

	<div class="footer">

		<img id="footer-logo" alt="Summit Bodyworks" src="<?php echo Mage::getDesign()->getSkinUrl('images/summit-logo-inverted.png'); ?>">

		<div id="footer-content">

			<div id="footer-mission">
				<h3>Summit Bodyworks Mission</h3>
				<p>As the nation's premier builder of specialty vehicles across a wide range of industries, Summit Bodyworks' goal is to exceed your expectations in everything we do. Each custom vehicle we build is unsurpassed in quality and functionality only matched by the service and support you'll receive from us every step of the way.</p>
				<h3>Going way beyond the extra mile</h3>
			</div>

			<div id="footer-vcard" class="vcard">
				<dl class="aligned">
					<dt>Toll-Free:</dt>
					<dd class="tel">866-514-8184</dd>
					<dt>Phone:</dt>
					<dd class="tel">303-301-7550</dd>
					<dt>Fax:</dt>
					<dd class="tel">303-288-2847</dd>
				</dl>
				<dl>
					<dt class="hq">Headquarters:</dt>
					<dd class="hq">
						<span class="street-address">
							6691 Colorado Blvd
						</span>
						<br>
						<span class="locality">
							Commerce City,
						</span>
						<span class="region">
							CO
						</span>
						<br>
						<span class="postal-code">
							80022
						</span>
						<span class="country-name">
							United States
						</span>
						<br>
						<a href="https://maps.google.com/maps?q=6691+Colorado+Blvd+Commerce+City,+CO+80022&ie=UTF-8&hq=&hnear=0x876c79f8dea50a7b:0xf33bd33421058664,6691+Colorado+Blvd,+Commerce+City,+CO+80022&gl=us&ei=0wodUvKRH-HsyQHT3ICIBA&ved=0CCsQ8gEwAA">map</a>
					</dd>
				</dl>
			</div>
		
			<div id="footer-nav">
	    		<?php echo $this->getChildHtml() ?>
	    	</div>

	    	<div style="clear:both"></div>

	    </div>

		<p>&copy; Transwest 2013</p>
	
	</div>

</div>
