<div class="call">
	<h3><?php echo $this->__('Call Us') ?>:</h3>
	<span><?php echo $this->__('Toll-Free') ?>:</span> <span><?php echo $this->__('866-514-8184') ?></span>
	<span><?php echo $this->__('Phone') ?>:</span> <span><?php echo $this->__('303-301-7550') ?></span>
	<span><?php echo $this->__('Fax') ?>:</span> <span><?php echo $this->__('303-288-2847') ?></span>
</div>
<div class="addr">
	<h3><?php echo $this->__('Headquarters') ?>:</h3>
	<span class="street-address">6691 Colorado Blvd</span>
	<br>
	<span class="locality">Commerce City,</span>
	<span class="region">CO</span>
	<br>
	<span class="postal-code">80022</span>
	<span class="country-name">United States</span>
	<br>
	<a href="https://maps.google.com/maps?q=6691+Colorado+Blvd+Commerce+City,+CO+80022&ie=UTF-8&hq=&hnear=0x876c79f8dea50a7b:0xf33bd33421058664,6691+Colorado+Blvd,+Commerce+City,+CO+80022&gl=us&ei=0wodUvKRH-HsyQHT3ICIBA&ved=0CCsQ8gEwAA"><?php echo $this->__('map') ?></a>
</div>