<div class="call">
	<h3><?php echo $this->__('Call Us') ?>:</h3>
	<span><?php echo $this->__('Toll-Free') ?>:</span> <span><?php echo $this->__('866-514-8184') ?></span>
	<span><?php echo $this->__('Phone') ?>:</span> <span><?php echo $this->__('303-301-7550') ?></span>
	<span><?php echo $this->__('Fax') ?>:</span> <span><?php echo $this->__('303-288-2847') ?></span>
</div>
<div class="addr">
	<h3><?php echo $this->__('Headquarters') ?>:</h3>
	<span class="street-address">7740 Dahlia St.</span>
	<br>
	<span class="locality">Commerce City,</span>
	<span class="region">CO</span>
	<br>
	<span class="postal-code">80022</span>
	<span class="country-name">United States</span>
	<br>
	<a href="https://www.google.com/maps/place/7740+Dahlia+St,+Commerce+City,+CO+80022/@39.8372572,-104.9305922,17z/data=!3m1!4b1!4m2!3m1!1s0x876c70b1c93723a3:0x73076c36c773cc99"><?php echo $this->__('map') ?></a>
</div>
